import GoogleSignIn from '@/components/GoogleSignIn'
import Login from '@/components/Login'
import { getAppAuth, uiConfig } from '@/firebaseConfig'
import { Heading, VStack } from '@chakra-ui/react'
import Head from 'next/head'
import { StyledFirebaseAuth } from 'react-firebaseui'

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<VStack flex={1} bg={'gray.900'} py={8}>
				<Heading fontSize={'8xl'}>Welcome</Heading>
				<GoogleSignIn />
			</VStack>
		</>
	)
}
