import HulloDatabase from '@/components/HulloDatabase'
import SignIn from '@/components/SignIn'
import { Heading, Image, Spacer, VStack } from '@chakra-ui/react'
import Head from 'next/head'

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<VStack flex={1} bg={'pink.200'} color={'red'} pt={16} spacing={8}>
				<Heading fontSize={'8xl'}>Welcome</Heading>
				<SignIn />
				<HulloDatabase />
				<Spacer />
				<Image src={'/ground.png'} alt={'An image of a grassy hill'} />
			</VStack>
		</>
	)
}

Home.noHeader = true
